#! /usr/bin/bash 

pacman --noconfirm -Syy

# Desktop 
pacman --noconfirm -S --needed xorg-server xorg-xinit xf86-video-intel lxqt sddm

# Fonts 
pacman --noconfirm -S --needed ttf-inconsolata 

# Audio 
pacman --noconfirm -S --needed pavucontrol pulseaudio pulseaudio-alsa

# NetworkManager 
pacman --noconfirm -S --needed networkmanager
systemctl enable NetworkManager

# Media 
pacman --noconfirm -S --needed vlc alsa-oss alsa-lib lib32-alsa-oss qt4

# Browser 
pacman --noconfirm -S --needed firefox 

# Utils 
pacman --noconfirm -S --needed redshift sakura youtube-dl screenfetch speedtest-cli cmatrix clamav git gparted kodi

pacman --noconfirm -Syyu
pacman --noconfirm -Rns $(pacman -Qdtq)
echo
echo
echo
echo "By Lecter."
