#! /usr/bin/bash 

pacman --noconfirm -Syy

# Desktop 
pacman --noconfirm -S --needed xorg-server xorg-xinit xf86-video-intel lxde lxdm 

# Fonts 
pacman --noconfirm -S --needed ttf-inconsolata 

# Audio 
pacman --noconfirm -S --needed pavucontrol pulseaudio pulseaudio-alsa

# Browser 
pacman --noconfirm -S --needed  qupzilla

# Utils 
pacman --noconfirm -S --needed redshift screenfetch cmatrix clamav kodi

pacman --noconfirm -Syyu
pacman --noconfirm -Rsn $(pacman -Qqdt)
echo
echo
echo
echo "By Lecter."
